### ISSUE TITLE
Question about factorial ANOVAs in MES Toolbox

### ISSUE THREAD

**Issue by wildetudor** [hhentschke/measures-of-effect-size-toolbox#2]
Hi Harald,

Thanks for this great toolbox! I ran the example code and have some difficulties with it that I hope you can help me with:

1) The documentation mentions that if the samples in X are dependent, the number of samples in each group of X must be equal. But, can I still somehow compute effect sizes when my data is unbalanced along the within-subjects factor, e.g. missing data in one of the repeated measures? 

2) When asking for partial eta-squared, the output table lists each contrast as psi1, psi2 etc, but Psi is defined as an altogether different measure of effect size!?

3) If I run the dependent-samples code at p.29:
mes1way(com_post,'partialeta2','group',group,'cWeight',[1 -1 0; 1 0 -1], 'isDep',1,'nBoot',10000) 
, the outputs appear under "between-groups".  Is this a bug in the script, or is "group" here, by virtue of isDep being 1, meant to be understood as "condition", i.e. as repeated measures of the same group? If so, what is the meaning of the "within groups" lines?

4) Is it at all possible to run ANOVAs with more than 2-factors? There isn't a mes3way.m, but can one do it in some other way?

5) I was taught that significant interaction are to be followed-up (decomposed) by making comparisons, for each level of one factor, between the levels of the remaining factor. The documentation does not make any reference to 'decomposition' of interactions, but the contrast configuration that (for some reason!) is referred to as 'simple' seems to do just that!? 

Thanks so much in advance for your answers!
Tudor

**Comment by hhentschke** [comment]
Hi Tudor,

thanks for your nice words. Prelude: I recently switched from academia (ample paid time for developing and sustaining open-access code like the mes toolbox) to a freelancing carreer as a Data Scientist (quite the opposite). So, while I'm still quite attached to the mes toolbox, my time for sustaining it is limited. With that being said:

1. You cannot, by definition. Your options are a) imputation of values (beyond the scope of the mes toolbox), and b) leaving out values with missing 'partners'.

2. Yes, alright, the output of mes1way is in fact a little ambiguous. The logic is this: if you go to the trouble of specifying contrast weights and request just partial eta squared (pe2), you'll want to get not only the overall (omnibus) pe2 but also those of the contrasts, and this is what is listed in the table. The mes you have in mind - the unstandardized contrasts termed psi, or the standardized contrasts termed g_psi - will be furnished if you specify them explicitly. Study the output of this:

mes1way(com_post,{'psi', 'g_psi','partialeta2'},'group',group,'cWeight',[1 -1 0; 1 0 -1], 'isDep',1,'nBoot',10000)

Here, psi, g_psi and their CI95 will be listed in the table (as column headers), alongside the contrast-based values of pe2. So, in short, intelligibility of the output suffers somewhat from the desire to present all results in a systematic way in a 'table' (cell array).

3. We adhered to the nomenclature in Kline (2005), see e.g Table 6.5 (p.175), if you have access to it. So, even if it is indeed a repeated measures of the same group, it is termed between-groups. Within-groups values: for example, within-groups summed squares (SS) of subjects ('-subj') describe the variability of the subjects (with respect to the grand average). For details, I'll have to refer you to Kline or any other in-depth book on the matter.

4. For n>2 things get really complex and costly timewise. Back when we developed the toolbox, the reasoning was that 2-way problems are common enough to justify the effort, but developing code for n>3 was out of the question. You can of course always compute specific mes from the outputs of anovas (e.g. Matlab's anovan).

5. Yes, you could interpret simple contrasts (nomenclature not our invention - read the papers/books!) as a means of an (uncorrected) post-hoc test, or decomposition of interactions. As to corrections for multiple comparisons: the question of how to conduct post-hoc tests properly is so controversial that we decided to keep our fingers off it. Anyone who deems one or the other correction for multiple comparisons superior to the other must implement it him-/herself. 

Hope that clarified things! If it did, could you please close the issue?
Best,

Harald

**Comment by wildetudor** [comment]
Hi Harald,

Thank you very much for your very helpful reply - I really appreciate it, all the more since this no longer directly constitutes work for you. Best of luck with the new job by the way.

Your answers address my questions perfectly. Before closing the issue, may I just clarify three final things: 

1) for a 3-level factor, the documentation suggests unbalanced c weights, e.g. [1 -0.5 -0.5]. Do permutations of that, e.g. [-0.5 1 -0.5], make a difference in the outputs, and/or create any bias towards the level that gets 1? Whatever the weights, however, non-significant effects always have CIs for partial-eta2 that do _not_ contain 0, which is perhaps a warning sign.

2) When asking for a specific contrast, say [1 -0.5 -0.5] corresponding to a main effect of the treatmentGroup factor, I get an entry 'contrast' (and its subentry '-main2'), the values of which (p, p_eta2 etc) are different from the values that are by default (even without asking for a contrast) displayed under the '- treatmentGroup' line, under the 'between-subjects' category (screenshot attached). Which of these rows should I believe?! 

3) The reported df seem strange: for the 3-element contrast used above, I get df=1 instead of df=2. And if I use an interaction contrast, that too gets df=1 whereas the corresponding gender*treatmentGroup line (under 'between-subjects') gets df=2! Finally, only one error (within-cells) df is reported, whereas I think there should be a separate one for each effect?!

Thanks again for your very kind help!
Tudor
![17-11-2019 18 36 17](https://user-images.githubusercontent.com/15835348/69011341-c0422d80-0969-11ea-9416-29bcfba20d3e.jpg)

**Comment by hhentschke** [comment]
Hi Tudor,
I believe that you can and should answer most of your questions by delving into books and the formulae yourself, especially on on contrasts, as they are not specific to the mes toolbox. Briefly, partial eta squared, and even more so the lower bound of its confidence interval, are by definition >=0, and will almost never be exactly zero, and that has no bearing on the 'significance' of the differences between the underlying groups. For this issue, please read the section 'Confidence intervals' in the documentation (p. 3) for a starting point. For the other issues, you'll find the sources we refer to in the references. Please understand that I cannot provide a tutorial on statistics here.
Best,

Harald

**Comment by wildetudor** [comment]
Alright, thanks Harald. For the record, my questions were those of someone who had read the documentation (not entirely, but a good chunk of it), and who has decent knowledge of stats, and since those resources provided no clarification, I imagined that other users might have the same issues. In either case, thanks again!
